In [20]:
@tdmclient.notebook.sync_var
def set_speed(left, right):
    global motor_left_target, motor_right_target
    motor_left_target = left
    motor_right_target = right

In [101]:
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 28 17:03:23 2021

@author: henry papapatos
"""
import numpy as np
import sys
#sys.path.append(r'C:\Users\Usuario\OneDrive - epfl.ch\Documents\EPFL\Basics of mobile robotics\PROJET\Github\Mobile_robotics')
import math
import cv2 
import time
import importlib
import filters 
import computer_vision
import path_planning

TRESH_DIST = 3 #mm
CAMERA = 0 # Camera

def main():
         
    try:              
        frame_init = computer_vision.get_image(cap)
        
        # we need to wait a bit otherwise the image is yellow 
        time.sleep(1)
        
        print("take the rigth image")
        frame_init = computer_vision.get_image(cap)
        
        #frame_init = cv2.cvtColor(frame_init, cv2.COLOR_BGR2RGB)
        frame_init_crop = cv2.resize(frame_init,None, fx=0.5, fy= 0.5, interpolation = cv2.INTER_CUBIC)

        cv2.imshow('frame', frame_init_crop)
        
        cv2.waitKey(0)
        
        cv2.imwrite(r'C:\Users\papad\OneDrive\Images\Pellicule\img.jpg', frame_init) #POUR TUNING PAR ELIOTT
        
        # Extract vertexes, goals, thymio's start position and orientation from first frame
        start_pos, obst_vertexes, goals_pos, px_to_mm = computer_vision.Init(frame_init)
        
        computer_vision.display_obstacle(frame_init, start_pos, goals_pos, obst_vertexes)
        
        frame_init_crop = cv2.resize(frame_init,None, fx=0.5, fy= 0.5, interpolation = cv2.INTER_CUBIC)
        
        cv2.imshow('frame', frame_init_crop)
        
        cv2.waitKey(0)
        
        cv2.imwrite(r'C:\Users\papad\OneDrive\Images\Pellicule\img_obstacle.jpg', frame_init) #POUR TUNING PAR ELIOTT
        
        goal_list = path_planning.get_optimal_path(start_pos, goals_pos, obst_vertexes, 
                                                   px_to_mm, draw = True, image = frame_init)
        
        frame_init_crop = cv2.resize(frame_init,None, fx=0.5, fy= 0.5, interpolation = cv2.INTER_CUBIC)
        
        cv2.imwrite(r'C:\Users\papad\OneDrive\Images\Pellicule\img_path.jpg', frame_init) #POUR TUNING PAR ELIOTT

        cv2.imshow('frame', frame_init_crop)
        
        cv2.waitKey(0)
        
        frame = computer_vision.get_image(cap)
        
        # The estimated state vector at time t-1 in the global reference frame.
        # [x_t_minus_1, y_t_minus_1, yaw_t_minus_1]
        x_est_t_minus_1, hidden_cam = computer_vision.vision(frame, px_to_mm)
        # x_est_t_minus_1 = np.array([0.0,0.0,0.0])
        
        # The control input vector at time t-1 in the global reference frame.
        # [v, yaw_rate]
        u_t_minus_1 = np.array([0 ,0])
         
        # State covariance matrix P_t_minus_1
        P_t_minus_1 = np.array([[0.1,  0,   0],
                                [  0,0.1,   0],
                                [  0,  0, 0.1]])
    
    
        #update le dt car sinon kalman marche pas
        dt = 0.1 # EN SECONDES POUR KALMAN!!!!! same as PI_CLOCK of pid defined in filters?
        sum_error = 0 
        alt_error_pid = 0
        
        time.sleep(0.1)
        
        while len(goal_list)!=0:
            
            print("goal is: ", goal_list[0])
            
            previous = time.time()
            
            frame = computer_vision.get_image(cap)
            
#             cv2.imshow('running frame', frame)

                
            ##### APPELER get_vision_position##########
            obs_vector_z_t, hidden_cam = computer_vision.vision(frame, px_to_mm)
            
            
            computer_vision.display_obstacle(frame, start_pos, goals_pos, obst_vertexes)
            
            computer_vision.display_pos(frame,obs_vector_z_t, px_to_mm, is_from_camera = True)
            
            
#             print(f'Timestep measurement={obs_vector_z_t}')
    
            # Run the Extended Kalman Filter and store the 
            # near-optimal state and covariance estimates
            optimal_state_estimate_t, covariance_estimate_t = filters.ekf(
                obs_vector_z_t, # Most recent sensor measurement
                x_est_t_minus_1, # Our most recent estimate of the state
                u_t_minus_1, # Our most recent control input
                P_t_minus_1, # Our most recent state covariance matrix
                dt,hidden_cam) # Time interval
            
            computer_vision.display_pos(frame, optimal_state_estimate_t, px_to_mm, is_from_camera = False)
            
            cv2.imshow('running frame', frame)
            
            if np.linalg.norm(np.array([optimal_state_estimate_t[0],optimal_state_estimate_t[1]])-np.array(goal_list[0])) < TRESH_DIST:
                goal_list.pop(0)
                
            # Get ready for the next timestep by updating the variable values
            x_est_t_minus_1 = optimal_state_estimate_t
            P_t_minus_1 = covariance_estimate_t
            
            #check if obstacle in coming
            
            #if no
            ######APPELER PID##########
            print()
            sum_error, alt_error_pid, v_l,v_d = filters.pid(optimal_state_estimate_t,goal_list[0],sum_error, alt_error_pid,dt)
            v = (v_l + v_d)*SPEED_TO_MMS/2
            yaw = (v_d - v_l)*YAW_TO_MMS
            u_t_minus_1 = [v, yaw]; # delta_v returned by PID
#             u_t_minus_1 = 0;
            set_speed(v_l, v_d)
    
            #if yes, obstacle avoidance 
            
            actual = time.time()
            diff = actual-previous
            print("elapsed time is: ", diff)
            time.sleep(dt-diff)
            
    finally: 
        cv2.destroyAllWindows()



In [10]:
print('Connecting to camera...')
cap=cv2.VideoCapture(CAMERA) # Either 0 or 1, front camera or external cam
print('Camera connected !')

Connecting to camera...
Camera connected !


In [11]:
#get the full quality of the camera
print("setting parameters...")
cap.set(3,1920) 
print("first parameter set")
cap.set(4,1080)
print("second parameter set")

setting parameters...
first parameter set
second parameter set


In [19]:
import tdmclient.notebook
print("connecting to thymio")
await tdmclient.notebook.start()

connecting to thymio


In [102]:
importlib.reload(filters)
importlib.reload(path_planning)
importlib.reload(computer_vision)

<module 'computer_vision' from 'C:\\Users\\papad\\OneDrive\\Documents\\MA1\\Basic_of_mobile_robotics\\project\\Mobile_robotics\\computer_vision.py'>

In [103]:
main()

take the rigth image


100%|██████████| 2/2 [00:00<00:00, 822.90it/s]


new_measure
[[[329 135]]

 [[382 144]]

 [[360 107]]]
[[[332  80]]

 [[312  76]]

 [[280 128]]

 [[299 133]]]
corners is:  [[[329 135]]

 [[382 144]]

 [[360 107]]]
goal is:  [145.545  49.628]
new_measure
[[[330 134]]

 [[382 143]]

 [[359 106]]]
[[[332  80]]

 [[312  76]]

 [[280 128]]

 [[299 133]]]
corners is:  [[[330 134]]

 [[382 143]]

 [[359 106]]]
pos robot is:  [145.513  49.597  24.276]
angle is:  [-1.848 -0.228]


TypeError: only size-1 arrays can be converted to Python scalars

Error in callback <function _post_run_cell at 0x0000019C988B08B0> (for post_run_cell):


ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

In [8]:
cap.release()